name: Build Angular App with Docker

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: macos-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Install Docker
          run: |
            brew install --cask docker
            open /Applications/Docker.app
            while ! docker system info > /dev/null 2>&1; do
              echo "Waiting for Docker to start..."
              sleep 1
            done

        - name: Log in to DockerHub
          run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

        - name: Build Docker image
          run: docker build --build-arg ENVIRONMENT=prod -t angular-app:latest .

        - name: Show docker images
          run: docker images