name: Angular-app-custom

on:
    workflow_dispatch:
        inputs:
            environments:
                description: 'Comma-separated list of environments to deploy to (e.g., dev, staging, prod)'
                default: '["dev"]'
                type: string
            sha:
                description: 'Commit SHA to deploy'
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                environment: ${{ fromJson(github.event.inputs.environments || '["dev"]') }}

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            ref: ${{ github.event.inputs.sha }}

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '22.12.0'
        
        - name: Install Angular CLI
          run: npm install -g @angular/cli

        - name: Install dependencies
          run: npm install

        - name: Build Angular app for ${{ matrix.environment }}
          run: ng build --progress=false -c=${{ matrix.environment }} --output-path=dist${{ matrix.environment }} --base-href=/

        - name: Upload ${{ matrix.environment }} artifact
          uses: actions/upload-artifact@v4
          with:
                path: dist${{ matrix.environment }}
                name: artifact-${{ matrix.environment }}-${{ github.run_number }}

    deploy: 
        runs-on: ubuntu-24.04
        needs: build
        strategy:
            matrix:
                environment: ${{ fromJson(github.event.inputs.environments || '["dev"]') }}
        environment: ${{ matrix.environment }}

        steps:
        - name: Deploy to ${{ matrix.environment }}
          run: echo "Deploy step for ${{ matrix.environment }} environment"
