name: Build Angular App with Docker

on:
  workflow_dispatch:
    inputs:
        environments:
            description: 'Comma-separated list of environments to deploy to e.g. ["dev", "qa", "prod"]'
            required: false
            type: string
        sha:
            description: 'Commit SHA to deploy'
            required: false
            type: string

  push:
        branches:
            - main
  pull_request:
        branches:
            - main

jobs:
    Dev-build:
        if : ${{ github.event.inputs.environments == ''}}
        runs-on: ubuntu-20.04
        env:
            ENVIRONMENT: dev
        
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
              
          - name: Build and push Docker image
            uses: docker/build-push-action@v2
            with:
              context: .
              push: true
              tags: harishtw/angular-app-${{ env.ENVIRONMENT }}:${{ github.run_number }}
              build-args: ENVIRONMENT=${{ env.ENVIRONMENT }}


    matrix-build:
        runs-on: ubuntu-20.04
        if: ${{ github.event.inputs.environments }}
        strategy:
            matrix:
                environment: ${{ fromJson(github.event.inputs.environments)}}
                
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
              ref: ${{ github.event.inputs.sha }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
              
          - name: Build and push Docker image
            uses: docker/build-push-action@v2
            with:
              context: .
              push: true
              tags: harishtw/angular-app-${{matrix.environment}}:${{ github.run_number }}
              build-args: ENVIRONMENT=${{matrix.environment}}