name: Angular-app-deploy
on:
    workflow_run:
        workflows: ["Angular-app-build"]
        types:
            - completed

jobs:
    deploy-dev:
        runs-on: ubuntu-22.04
        environment: DEV
        steps:
            - name: Deploy to Dev
              run: echo "Development deployment successful"

            - name: Download artifact
              id: download-artifact
              uses: actions/download-artifact@v3
              with:
                name: angular-app-dev-${{ github.run_number }}.zip
                path: ./artifact
            
            - name: Unzip artifact
              run: unzip ./artifact/angular-app-dev-${{ github.run_number }}.zip -d ./artifact
            
            - name: Artifact contents
              run: ls -l ./artifact


    deploy-qa:
        needs: deploy-dev
        runs-on: ubuntu-22.04
        environment: QA
        steps:
           - name: Deploy to QA
             run: echo "Testing deployment successful"

    deploy-prod:
        needs: deploy-qa
        runs-on: ubuntu-22.04
        environment: PROD
        steps:
          - name: Deploy to Prod
            run: echo "Production deployment successful"