name: Angular-app-deploy
on:
    workflow_run:
        workflows: ["Angular-app-build"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                environment: [dev, qa, prod] # List all possible environments here
        environment: ${{ matrix.environment }}
        steps:
            - name: Set environment variable
              run: echo "ENVIRONMENT=${{ matrix.environment }}" | tr '[:lower:]' '[:upper:]' >> $GITHUB_ENV
            - name: Deploy to ${{ env.ENVIRONMENT }}
              if: contains(github.event.workflow_run.conclusion, 'success')
              run: echo "${{ env.ENVIRONMENT }} deployment successful"
