name: Deploy Angular App to ECS

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
            
            - name: Log in to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build and Push Docker image
              run: |
                IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:latest
                docker build -t $IMAGE_URI .
                docker push $IMAGE_URI

            - name: Deploy to ECS
              uses: aws-actions/amazon-ecs-deploy-task-definition@v1
              with:
                  cluster: angular-app
                  service: angular-app
                  task-definition: |
                    {
                      "family": "angular-app-task-definition",
                      "containerDefinitions": [
                        {
                          "name": "angular-app",
                          "image": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:latest",
                          "memory": 512,
                          "cpu": 256,
                          "essential": true
                        }
                      ]
                    }
                  wait-for-service-stability: true