name: Angular-app-build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - uat
          - prod
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.12.0'
    
    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm install

    - name: Build Angular app for ${{ github.event.inputs.environment }}
      run: ng build --progress=false -c=${{ github.event.inputs.environment }} --output-path=dist${{ github.event.inputs.environment }} --base-href=/

    - name: Upload ${{ github.event.inputs.environment }} artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: angular-app-${{ github.event.inputs.environment }}-${{ github.run_number }}.zip
        path: dist${{ github.event.inputs.environment }}/
