name: Angular-app-deploy
on:
    workflow_run:
        workflows: ["angular-app-build"]
        types:
            - completed

jobs:
    deploy-dev:
        runs-on: ubuntu-22.04
        environment: DEV
        steps:
            - name: Deploy to Dev
              run: echo "Development deployment successful"

    deploy-qa:
        needs: deploy-dev
        runs-on: ubuntu-22.04
        environment: QA
        steps:
           - name: Deploy to QA
             run: echo "Testing deployment successful"

    deploy-prod:
        needs: deploy-qa
        runs-on: ubuntu-22.04
        environment: PROD
        steps:
          - name: Deploy to Prod
            run: echo "Production deployment successful"