name: Angular-app-deploy
on:
    workflow_run:
        workflows: ["Angular-app-build"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v3
              with:
                  name: built-environments
                  path: ./built-environments

            - name: Read built environments
              id: read-envs
              run: |
                  BUILT_ENVS=$(cat ./built-environments/environments.txt)
                  echo "BUILT_ENVS=$BUILT_ENVS" >> $GITHUB_ENV

            - name: Deploy to built environments
              if: contains(github.event.workflow_run.conclusion, 'success')
              run: |
                  for ENV in $BUILT_ENVS; do
                      echo "Deploying to $ENV"
                      # Add your deployment script/command here
                      echo "$ENV deployment successful"
                  done
