name: Angular-app-build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
  MATRIX_ENV: dev,qa,prod

jobs:
  build:
    strategy:
      matrix:
        environment: [dev, qa, prod]
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.12.0'
    
    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm install

    - name: Build Angular app for ${{ matrix.environment }}
      run: ng build --progress=false -c=${{ matrix.environment }} --output-path=dist${{ matrix.environment }} --base-href=/

    - name: Upload ${{ matrix.environment }} artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: angular-app-${{ matrix.environment }}-${{ github.run_number }}.zip
        path: dist${{ matrix.environment }}/
